# Generated by Django 4.2 on 2023-04-23 22:07

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(db_index=True, max_length=55)),
                ('subject', models.CharField(choices=[('app support', 'App Support'), ('payment support', 'Payment Support'), ('HR/Jobs', 'HR & Jobs'), ('other', 'Non related (Other)')], max_length=15)),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progres', 'In Progres - somone is taking an action'), ('Resolved', 'Resolved - action was made')], default='New', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
